---
- name: Install nginx
  become: yes
  block:
    - name: Set repository
      become: true
      template:
        src: "{{templates_source}}"
        dest: "/etc/yum.repos.d/nginx.repo"
        backup: yes
        mode: 0644
        owner: root

    - name: Install nginx
      yum:
        name:
          - nginx
        state: present
