---
- name: Install nginx
  become: yes
  block:
    - name: set repository
      become: true
      template:
        src: "../templates/etc/yum.repos.d/nginx.repo.j2"
        dest: "/etc/yum.repos.d/nginx.repo"
        backup: yes
        mode: 0644
        owner: root

    # - name: Ensure directory structure exists
    #   file:
    #     path: "{{ item.root.split('templates')[1] }}/{{ item.path }}"
    #     state: directory
    #   with_filetree: "../templates/etc/yum.repos.d"
    #   when: item.state == "directory"
    #
    # - name: Ensure files are populated from templates
    #   template:
    #     src: "{{ item.src }}"
    #     dest: "{{ item.root.split('templates')[1] }}/\
    #        {{ item.path | regex_replace('\\.j2','') }}"
    #   with_filetree: "../templates/nginx"
    #   when: item.state == "file"

    - name: Install nginx
      yum:
        name:
          - nginx
        state: present


    - debug:
        msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
    - debug:
        msg: "{{ansible_architecture}}"
